FROM node:15.14.0-alpine3.10
WORKDIR /usr/src/app

COPY . .

RUN cd shared-modules && npm install && npm run build

WORKDIR /usr/src/app/ssi-bridge

RUN npm ci
RUN npm run build

CMD [ "node", "dist/ssi-bridge/src/index.js", "server" ]